-- ============================================================
-- COMBINED SUPABASE SQL
-- Generated by automated workspace cleanup.
-- Contains the contents of all individual .sql source files in this workspace.
-- Generated on 2026-05-22T02:02:44.932233Z
-- ============================================================

-- ============================================================
-- SOURCE: bootstrap_super_admin1.sql
-- ============================================================

-- ============================================================
-- SUPER ADMIN SETUP (choose ONE method)
-- ============================================================

-- ── METHOD A (recommended): Supabase Authentication → Add user ──
-- 1. Dashboard → Authentication → Users → Add user
-- 2. Email + password, tick "Auto Confirm User"
-- 3. Run: link_super_admin_from_auth.sql

-- ── METHOD B: SQL only (legacy, no Supabase Auth) ──
-- Uses werkzeug password hash in public.users only.
-- Default password: Admin@1234

/*
INSERT INTO users (email, password_hash, full_name, role, is_active)
VALUES (
    'superadmin@ttieportfolio.ac.ke',
    'scrypt:32768:8:1$qvQYsYQ4WnXc2Gud$a0da4d08aeca7dddee115d64f62a99571784c88622f1d32607f70fdfd660f4b4d3e75a4daec2f9a2ab1b51804df6208625bac575c5876bdf166cb200a26357ea',
    'Super Administrator',
    'super_admin',
    TRUE
)
ON CONFLICT (email) DO NOTHING;
*/



-- ============================================================
-- SOURCE: server\supabase\migrations\20260521000001_init_schema.sql
-- ============================================================





-- ============================================================
-- SOURCE: supabase_schema.sql
-- ============================================================

-- ============================================================
-- THIKA TECHNICAL TRAINING INSTITUTE
-- Attendance Management System — Supabase Schema
-- Run this entire file in the Supabase SQL Editor
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- 0. EXTENSIONS
-- ────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ────────────────────────────────────────────────────────────
-- 1. CORE LOOKUP TABLES
-- ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS departments (
    id   SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS classes (
    id            SERIAL PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    department_id INT NOT NULL REFERENCES departments(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS units (
    id            SERIAL PRIMARY KEY,
    code          VARCHAR(50)  NOT NULL UNIQUE,
    name          VARCHAR(200) NOT NULL,
    department_id INT REFERENCES departments(id) ON DELETE SET NULL
);

-- ────────────────────────────────────────────────────────────
-- 2. USER PROFILE TABLE
--    Mirrors auth.users; one row per Supabase Auth user.
--    role: 'super_admin' | 'dept_admin' | 'trainer' | 'student'
-- ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS user_profiles (
    id            UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name     VARCHAR(200),
    role          VARCHAR(20)  NOT NULL CHECK (role IN ('super_admin','dept_admin','trainer','student')),
    department_id INT REFERENCES departments(id) ON DELETE SET NULL,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Keep updated_at current automatically
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;

CREATE TRIGGER trg_user_profiles_updated_at
    BEFORE UPDATE ON user_profiles
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ────────────────────────────────────────────────────────────
-- 3. TRAINERS
--    Linked to a Supabase Auth user via user_id.
-- ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS trainers (
    id            SERIAL PRIMARY KEY,
    user_id       UUID UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
    name          VARCHAR(200) NOT NULL,
    username      VARCHAR(100) NOT NULL UNIQUE,
    department_id INT REFERENCES departments(id) ON DELETE SET NULL
);

-- ────────────────────────────────────────────────────────────
-- 4. STUDENTS
--    Linked to a Supabase Auth user via user_id.
-- ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS students (
    id               SERIAL PRIMARY KEY,
    user_id          UUID UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
    admission_number VARCHAR(50)  UNIQUE,
    full_name        VARCHAR(200),
    email            VARCHAR(100),
    class_id         INT REFERENCES classes(id) ON DELETE CASCADE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ────────────────────────────────────────────────────────────
-- 5. CLASS–UNIT ASSIGNMENTS
-- ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS class_units (
    id         SERIAL PRIMARY KEY,
    class_id   INT NOT NULL REFERENCES classes(id)   ON DELETE CASCADE,
    unit_id    INT NOT NULL REFERENCES units(id)     ON DELETE CASCADE,
    trainer_id INT NOT NULL REFERENCES trainers(id)  ON DELETE CASCADE,
    year       INT NOT NULL DEFAULT EXTRACT(YEAR FROM NOW())::INT,
    term       INT NOT NULL DEFAULT 1,
    UNIQUE (class_id, unit_id, trainer_id, year, term)
);

-- ────────────────────────────────────────────────────────────
-- 6. ATTENDANCE
-- ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS attendance (
    id              SERIAL PRIMARY KEY,
    student_id      INT NOT NULL REFERENCES students(id)  ON DELETE CASCADE,
    unit_id         INT NOT NULL REFERENCES units(id)     ON DELETE CASCADE,
    unit_code       VARCHAR(50),
    trainer_id      INT NOT NULL REFERENCES trainers(id)  ON DELETE CASCADE,
    lesson          VARCHAR(10) NOT NULL,
    week            INT NOT NULL,
    year            INT NOT NULL DEFAULT EXTRACT(YEAR FROM NOW())::INT,
    term            INT NOT NULL DEFAULT 1,
    status          VARCHAR(10) NOT NULL CHECK (status IN ('present','absent')),
    attendance_date TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ────────────────────────────────────────────────────────────
-- 7. CLASS EVENTS  (holidays / academic trips)
-- ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS class_events (
    id         SERIAL PRIMARY KEY,
    class_id   INT NOT NULL REFERENCES classes(id)   ON DELETE CASCADE,
    unit_id    INT NOT NULL DEFAULT 0,               -- 0 = applies to whole class
    trainer_id INT NOT NULL REFERENCES trainers(id)  ON DELETE CASCADE,
    event_type VARCHAR(30) NOT NULL CHECK (event_type IN ('holiday','academic_trip')),
    week       INT NOT NULL,
    lesson     VARCHAR(10) NOT NULL,
    year       INT NOT NULL DEFAULT EXTRACT(YEAR FROM NOW())::INT,
    term       INT NOT NULL DEFAULT 1,
    note       TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (class_id, unit_id, trainer_id, week, lesson, year, term)
);

-- ────────────────────────────────────────────────────────────
-- 8. SYSTEM AUDIT LOG
-- ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS system_logs (
    id         BIGSERIAL PRIMARY KEY,
    actor_id   UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    actor_role VARCHAR(20),
    action     VARCHAR(100) NOT NULL,
    target     VARCHAR(200),
    detail     JSONB,
    ip_address INET,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ────────────────────────────────────────────────────────────
-- 9. HELPER FUNCTIONS (used by RLS policies)
-- ────────────────────────────────────────────────────────────

-- Returns the role of the currently authenticated user
CREATE OR REPLACE FUNCTION current_user_role()
RETURNS TEXT LANGUAGE sql STABLE SECURITY DEFINER AS $$
    SELECT role FROM user_profiles WHERE id = auth.uid();
$$;

-- Returns the department_id of the currently authenticated user
CREATE OR REPLACE FUNCTION current_user_dept()
RETURNS INT LANGUAGE sql STABLE SECURITY DEFINER AS $$
    SELECT department_id FROM user_profiles WHERE id = auth.uid();
$$;

-- Returns TRUE if the current user is active
CREATE OR REPLACE FUNCTION current_user_active()
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER AS $$
    SELECT COALESCE(is_active, FALSE) FROM user_profiles WHERE id = auth.uid();
$$;

-- ────────────────────────────────────────────────────────────
-- 10. ROW LEVEL SECURITY
-- ────────────────────────────────────────────────────────────

ALTER TABLE departments   ENABLE ROW LEVEL SECURITY;
ALTER TABLE classes       ENABLE ROW LEVEL SECURITY;
ALTER TABLE units         ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE trainers      ENABLE ROW LEVEL SECURITY;
ALTER TABLE students      ENABLE ROW LEVEL SECURITY;
ALTER TABLE class_units   ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance    ENABLE ROW LEVEL SECURITY;
ALTER TABLE class_events  ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_logs   ENABLE ROW LEVEL SECURITY;

-- ── departments ──────────────────────────────────────────────

-- Super admin: full access
CREATE POLICY dept_super_admin ON departments
    FOR ALL TO authenticated
    USING (current_user_role() = 'super_admin' AND current_user_active())
    WITH CHECK (current_user_role() = 'super_admin' AND current_user_active());

-- Dept admin / trainer / student: read their own department only
CREATE POLICY dept_read_own ON departments
    FOR SELECT TO authenticated
    USING (
        current_user_active()
        AND current_user_role() IN ('dept_admin','trainer','student')
        AND id = current_user_dept()
    );

-- ── classes ──────────────────────────────────────────────────

CREATE POLICY classes_super_admin ON classes
    FOR ALL TO authenticated
    USING (current_user_role() = 'super_admin' AND current_user_active())
    WITH CHECK (current_user_role() = 'super_admin' AND current_user_active());

CREATE POLICY classes_dept_admin ON classes
    FOR ALL TO authenticated
    USING (
        current_user_active()
        AND current_user_role() = 'dept_admin'
        AND department_id = current_user_dept()
    )
    WITH CHECK (
        current_user_active()
        AND current_user_role() = 'dept_admin'
        AND department_id = current_user_dept()
    );

CREATE POLICY classes_read_own_dept ON classes
    FOR SELECT TO authenticated
    USING (
        current_user_active()
        AND current_user_role() IN ('trainer','student')
        AND department_id = current_user_dept()
    );

-- ── units ────────────────────────────────────────────────────

CREATE POLICY units_super_admin ON units
    FOR ALL TO authenticated
    USING (current_user_role() = 'super_admin' AND current_user_active())
    WITH CHECK (current_user_role() = 'super_admin' AND current_user_active());

CREATE POLICY units_dept_admin ON units
    FOR ALL TO authenticated
    USING (
        current_user_active()
        AND current_user_role() = 'dept_admin'
        AND department_id = current_user_dept()
    )
    WITH CHECK (
        current_user_active()
        AND current_user_role() = 'dept_admin'
        AND department_id = current_user_dept()
    );

CREATE POLICY units_read_own_dept ON units
    FOR SELECT TO authenticated
    USING (
        current_user_active()
        AND current_user_role() IN ('trainer','student')
        AND department_id = current_user_dept()
    );

-- ── user_profiles ────────────────────────────────────────────

-- Super admin: full access
CREATE POLICY profiles_super_admin ON user_profiles
    FOR ALL TO authenticated
    USING (current_user_role() = 'super_admin' AND current_user_active())
    WITH CHECK (current_user_role() = 'super_admin' AND current_user_active());

-- Dept admin: read/update profiles in their department
CREATE POLICY profiles_dept_admin ON user_profiles
    FOR SELECT TO authenticated
    USING (
        current_user_active()
        AND current_user_role() = 'dept_admin'
        AND department_id = current_user_dept()
    );

-- Any user: read/update their own profile
CREATE POLICY profiles_own ON user_profiles
    FOR ALL TO authenticated
    USING (id = auth.uid())
    WITH CHECK (id = auth.uid());

-- ── trainers ─────────────────────────────────────────────────

CREATE POLICY trainers_super_admin ON trainers
    FOR ALL TO authenticated
    USING (current_user_role() = 'super_admin' AND current_user_active())
    WITH CHECK (current_user_role() = 'super_admin' AND current_user_active());

CREATE POLICY trainers_dept_admin ON trainers
    FOR ALL TO authenticated
    USING (
        current_user_active()
        AND current_user_role() = 'dept_admin'
        AND department_id = current_user_dept()
    )
    WITH CHECK (
        current_user_active()
        AND current_user_role() = 'dept_admin'
        AND department_id = current_user_dept()
    );

CREATE POLICY trainers_read_own_dept ON trainers
    FOR SELECT TO authenticated
    USING (
        current_user_active()
        AND current_user_role() = 'trainer'
        AND department_id = current_user_dept()
    );

CREATE POLICY trainers_own_row ON trainers
    FOR SELECT TO authenticated
    USING (user_id = auth.uid() AND current_user_active());

-- ── students ─────────────────────────────────────────────────

CREATE POLICY students_super_admin ON students
    FOR ALL TO authenticated
    USING (current_user_role() = 'super_admin' AND current_user_active())
    WITH CHECK (current_user_role() = 'super_admin' AND current_user_active());

CREATE POLICY students_dept_admin ON students
    FOR ALL TO authenticated
    USING (
        current_user_active()
        AND current_user_role() = 'dept_admin'
        AND class_id IN (
            SELECT id FROM classes WHERE department_id = current_user_dept()
        )
    )
    WITH CHECK (
        current_user_active()
        AND current_user_role() = 'dept_admin'
        AND class_id IN (
            SELECT id FROM classes WHERE department_id = current_user_dept()
        )
    );

CREATE POLICY students_trainer_read ON students
    FOR SELECT TO authenticated
    USING (
        current_user_active()
        AND current_user_role() = 'trainer'
        AND class_id IN (
            SELECT cu.class_id FROM class_units cu
            JOIN trainers t ON t.id = cu.trainer_id
            WHERE t.user_id = auth.uid()
        )
    );

CREATE POLICY students_own_row ON students
    FOR SELECT TO authenticated
    USING (user_id = auth.uid() AND current_user_active());

-- ── class_units ──────────────────────────────────────────────

CREATE POLICY cu_super_admin ON class_units
    FOR ALL TO authenticated
    USING (current_user_role() = 'super_admin' AND current_user_active())
    WITH CHECK (current_user_role() = 'super_admin' AND current_user_active());

CREATE POLICY cu_dept_admin ON class_units
    FOR ALL TO authenticated
    USING (
        current_user_active()
        AND current_user_role() = 'dept_admin'
        AND class_id IN (
            SELECT id FROM classes WHERE department_id = current_user_dept()
        )
    )
    WITH CHECK (
        current_user_active()
        AND current_user_role() = 'dept_admin'
        AND class_id IN (
            SELECT id FROM classes WHERE department_id = current_user_dept()
        )
    );

CREATE POLICY cu_trainer_own ON class_units
    FOR SELECT TO authenticated
    USING (
        current_user_active()
        AND current_user_role() = 'trainer'
        AND trainer_id IN (SELECT id FROM trainers WHERE user_id = auth.uid())
    );

CREATE POLICY cu_student_read ON class_units
    FOR SELECT TO authenticated
    USING (
        current_user_active()
        AND current_user_role() = 'student'
        AND class_id IN (SELECT class_id FROM students WHERE user_id = auth.uid())
    );

-- ── attendance ───────────────────────────────────────────────

CREATE POLICY att_super_admin ON attendance
    FOR ALL TO authenticated
    USING (current_user_role() = 'super_admin' AND current_user_active())
    WITH CHECK (current_user_role() = 'super_admin' AND current_user_active());

CREATE POLICY att_dept_admin ON attendance
    FOR ALL TO authenticated
    USING (
        current_user_active()
        AND current_user_role() = 'dept_admin'
        AND student_id IN (
            SELECT s.id FROM students s
            JOIN classes c ON c.id = s.class_id
            WHERE c.department_id = current_user_dept()
        )
    )
    WITH CHECK (
        current_user_active()
        AND current_user_role() = 'dept_admin'
        AND student_id IN (
            SELECT s.id FROM students s
            JOIN classes c ON c.id = s.class_id
            WHERE c.department_id = current_user_dept()
        )
    );

CREATE POLICY att_trainer_own ON attendance
    FOR ALL TO authenticated
    USING (
        current_user_active()
        AND current_user_role() = 'trainer'
        AND trainer_id IN (SELECT id FROM trainers WHERE user_id = auth.uid())
    )
    WITH CHECK (
        current_user_active()
        AND current_user_role() = 'trainer'
        AND trainer_id IN (SELECT id FROM trainers WHERE user_id = auth.uid())
    );

CREATE POLICY att_student_own ON attendance
    FOR SELECT TO authenticated
    USING (
        current_user_active()
        AND current_user_role() = 'student'
        AND student_id IN (SELECT id FROM students WHERE user_id = auth.uid())
    );

-- ── class_events ─────────────────────────────────────────────

CREATE POLICY events_super_admin ON class_events
    FOR ALL TO authenticated
    USING (current_user_role() = 'super_admin' AND current_user_active())
    WITH CHECK (current_user_role() = 'super_admin' AND current_user_active());

CREATE POLICY events_dept_admin ON class_events
    FOR ALL TO authenticated
    USING (
        current_user_active()
        AND current_user_role() = 'dept_admin'
        AND class_id IN (
            SELECT id FROM classes WHERE department_id = current_user_dept()
        )
    )
    WITH CHECK (
        current_user_active()
        AND current_user_role() = 'dept_admin'
        AND class_id IN (
            SELECT id FROM classes WHERE department_id = current_user_dept()
        )
    );

CREATE POLICY events_trainer_own ON class_events
    FOR ALL TO authenticated
    USING (
        current_user_active()
        AND current_user_role() = 'trainer'
        AND trainer_id IN (SELECT id FROM trainers WHERE user_id = auth.uid())
    )
    WITH CHECK (
        current_user_active()
        AND current_user_role() = 'trainer'
        AND trainer_id IN (SELECT id FROM trainers WHERE user_id = auth.uid())
    );

-- ── system_logs ──────────────────────────────────────────────

-- Only super_admin can read logs; backend service role writes them
CREATE POLICY logs_super_admin_read ON system_logs
    FOR SELECT TO authenticated
    USING (current_user_role() = 'super_admin' AND current_user_active());

-- ────────────────────────────────────────────────────────────
-- 11. AUTO-CREATE user_profile ON SIGNUP
--     Triggered by Supabase Auth new user event.
--     Wrapped in EXCEPTION so a trigger failure never blocks
--     user creation.  Role is validated before insert.
-- ────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION handle_new_auth_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_role      TEXT;
    v_full_name TEXT;
BEGIN
    -- Safely read role from metadata; default to 'student'
    v_role := COALESCE(
        NULLIF(TRIM(NEW.raw_user_meta_data->>'role'), ''),
        'student'
    );

    -- Clamp to valid values — never let bad metadata crash the trigger
    IF v_role NOT IN ('super_admin','dept_admin','trainer','student') THEN
        v_role := 'student';
    END IF;

    v_full_name := COALESCE(
        NULLIF(TRIM(NEW.raw_user_meta_data->>'full_name'), ''),
        NEW.email
    );

    INSERT INTO public.user_profiles (id, full_name, role, is_active)
    VALUES (NEW.id, v_full_name, v_role, TRUE)
    ON CONFLICT (id) DO NOTHING;

    RETURN NEW;
EXCEPTION WHEN OTHERS THEN
    -- Log the error but never block user creation
    RAISE WARNING 'handle_new_auth_user failed for %: %', NEW.id, SQLERRM;
    RETURN NEW;
END;
$$;

-- Drop and recreate trigger cleanly
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION handle_new_auth_user();

-- ────────────────────────────────────────────────────────────
-- 12. SEED: PROMOTE AN EXISTING USER TO SUPER ADMIN
--
-- STEP 1: Go to Supabase Dashboard → Authentication → Users
--         Click "Add user" → enter email + password → Save
--
-- STEP 2: Copy the UUID shown in the users list
--
-- STEP 3: Run this block in SQL Editor (replace the UUID and name):
-- ────────────────────────────────────────────────────────────

/*
INSERT INTO public.user_profiles (id, full_name, role, department_id, is_active)
VALUES (
    'PASTE-UUID-HERE',   -- UUID from auth.users
    'Super Admin',       -- display name
    'super_admin',
    NULL,
    TRUE
)
ON CONFLICT (id) DO UPDATE
    SET role      = 'super_admin',
        is_active = TRUE;
*/

-- ── ALTERNATIVE: promote by email (run after user exists in auth.users) ──────
/*
UPDATE public.user_profiles
SET    role = 'super_admin', is_active = TRUE
WHERE  id = (
    SELECT id FROM auth.users WHERE email = 'your-admin@email.com'
);
*/

-- ────────────────────────────────────────────────────────────
-- 13. USEFUL VIEWS
-- ────────────────────────────────────────────────────────────

-- Department summary (used by super_admin dashboard)
CREATE OR REPLACE VIEW v_department_stats AS
SELECT
    d.id,
    d.name,
    COUNT(DISTINCT c.id)  AS class_count,
    COUNT(DISTINCT s.id)  AS student_count,
    COUNT(DISTINCT t.id)  AS trainer_count
FROM departments d
LEFT JOIN classes  c ON c.department_id = d.id
LEFT JOIN students s ON s.class_id = c.id
LEFT JOIN trainers t ON t.department_id = d.id
GROUP BY d.id, d.name
ORDER BY d.name;

-- Student attendance summary per unit
CREATE OR REPLACE VIEW v_student_attendance_summary AS
SELECT
    s.id          AS student_id,
    s.admission_number,
    s.full_name,
    u.id          AS unit_id,
    u.code        AS unit_code,
    u.name        AS unit_name,
    COUNT(*)      AS total_records,
    SUM(CASE WHEN a.status = 'present' THEN 1 ELSE 0 END) AS attended,
    MAX(a.attendance_date) AS last_update
FROM attendance a
JOIN students s ON s.id = a.student_id
JOIN units    u ON u.id = a.unit_id
GROUP BY s.id, s.admission_number, s.full_name, u.id, u.code, u.name;

-- ────────────────────────────────────────────────────────────
-- 14. INDEXES FOR PERFORMANCE
-- ────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_attendance_student   ON attendance(student_id);
CREATE INDEX IF NOT EXISTS idx_attendance_unit      ON attendance(unit_id);
CREATE INDEX IF NOT EXISTS idx_attendance_trainer   ON attendance(trainer_id);
CREATE INDEX IF NOT EXISTS idx_attendance_week_year ON attendance(week, year, term);
CREATE INDEX IF NOT EXISTS idx_students_class       ON students(class_id);
CREATE INDEX IF NOT EXISTS idx_classes_dept         ON classes(department_id);
CREATE INDEX IF NOT EXISTS idx_trainers_dept        ON trainers(department_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_role   ON user_profiles(role);
CREATE INDEX IF NOT EXISTS idx_user_profiles_dept   ON user_profiles(department_id);
CREATE INDEX IF NOT EXISTS idx_system_logs_actor    ON system_logs(actor_id);
CREATE INDEX IF NOT EXISTS idx_system_logs_created  ON system_logs(created_at DESC);



-- ============================================================
-- SOURCE: supabase_new_modules.sql
-- ============================================================

-- ============================================================
-- TTTTI — NEW MODULES SCHEMA
-- Modules: Exam Booking, Internal Verification, External Verification,
--          Dual Training, Industrial Attachment & Digital Logbook
-- Run in Supabase SQL Editor AFTER supabase_schema.sql
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- MODULE 5: EXAMINATION BOOKING
-- ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS exam_series (
    id          SERIAL PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,          -- e.g. "July/August 2026 CDACC"
    start_date  DATE NOT NULL,
    end_date    DATE NOT NULL,
    deadline    DATE NOT NULL,                  -- registration deadline
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS assessment_centers (
    id          SERIAL PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    location    VARCHAR(200),
    is_active   BOOLEAN NOT NULL DEFAULT TRUE
);

-- Insert default assessment center
INSERT INTO assessment_centers (name, location) VALUES
    ('Thika Technical Training Institute', 'Thika, Kiambu County')
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS exam_bookings (
    id                  SERIAL PRIMARY KEY,
    student_id          INT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    series_id           INT NOT NULL REFERENCES exam_series(id) ON DELETE CASCADE,
    center_id           INT REFERENCES assessment_centers(id) ON DELETE SET NULL,
    -- Candidate details (snapshot at booking time)
    full_name           VARCHAR(200) NOT NULL,
    admission_number    VARCHAR(50)  NOT NULL,
    course_code         VARCHAR(50),
    course_name         VARCHAR(200),
    module_level        VARCHAR(100),
    gender              VARCHAR(10),
    date_of_birth       DATE,
    mobile_number       VARCHAR(20),
    email               VARCHAR(100),
    national_id         VARCHAR(50),
    pwd_status          VARCHAR(50),
    -- Required uploads (Supabase Storage paths)
    national_id_doc     TEXT,   -- path to uploaded file
    birth_cert_doc      TEXT,
    kcse_cert_doc       TEXT,
    result_slip_doc     TEXT,
    fee_statement_doc   TEXT,
    -- Approval workflow
    status              VARCHAR(20) NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','hod_approved','registrar_approved','rejected')),
    hod_approved_by     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    hod_approved_at     TIMESTAMPTZ,
    hod_comment         TEXT,
    registrar_approved_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    registrar_approved_at TIMESTAMPTZ,
    registrar_comment   TEXT,
    -- QR code token for verification
    qr_token            VARCHAR(64) UNIQUE DEFAULT encode(gen_random_bytes(32), 'hex'),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (student_id, series_id)
);

CREATE TABLE IF NOT EXISTS exam_booking_units (
    id              SERIAL PRIMARY KEY,
    booking_id      INT NOT NULL REFERENCES exam_bookings(id) ON DELETE CASCADE,
    unit_id         INT NOT NULL REFERENCES units(id) ON DELETE CASCADE,
    unit_type       VARCHAR(20) DEFAULT 'Core' CHECK (unit_type IN ('Core','Common','Basic')),
    unit_cost       NUMERIC(10,2) DEFAULT 0,
    UNIQUE (booking_id, unit_id)
);

CREATE TRIGGER trg_exam_bookings_updated_at
    BEFORE UPDATE ON exam_bookings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ────────────────────────────────────────────────────────────
-- MODULE 8: INTERNAL VERIFICATION
-- ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS iv_assignments (
    id              SERIAL PRIMARY KEY,
    verifier_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    trainer_id      INT  NOT NULL REFERENCES trainers(id)   ON DELETE CASCADE,
    unit_id         INT  NOT NULL REFERENCES units(id)      ON DELETE CASCADE,
    class_id        INT  NOT NULL REFERENCES classes(id)    ON DELETE CASCADE,
    year            INT  NOT NULL DEFAULT EXTRACT(YEAR FROM NOW())::INT,
    term            INT  NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (verifier_id, trainer_id, unit_id, class_id, year, term)
);

CREATE TABLE IF NOT EXISTS iv_reviews (
    id              SERIAL PRIMARY KEY,
    assignment_id   INT  NOT NULL REFERENCES iv_assignments(id) ON DELETE CASCADE,
    student_id      INT  NOT NULL REFERENCES students(id)       ON DELETE CASCADE,
    -- Evidence verification
    evidence_status VARCHAR(20) NOT NULL DEFAULT 'pending'
                    CHECK (evidence_status IN ('pending','approved','rejected','needs_revision')),
    assessment_status VARCHAR(20) NOT NULL DEFAULT 'pending'
                    CHECK (assessment_status IN ('pending','approved','rejected','needs_revision')),
    comments        TEXT,
    recommendations TEXT,
    -- Digital signature (base64 or path)
    verifier_signature TEXT,
    signed_at       TIMESTAMPTZ,
    -- Compliance
    compliance_score INT CHECK (compliance_score BETWEEN 0 AND 100),
    version         INT NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (assignment_id, student_id)
);

CREATE TABLE IF NOT EXISTS iv_review_history (
    id          BIGSERIAL PRIMARY KEY,
    review_id   INT NOT NULL REFERENCES iv_reviews(id) ON DELETE CASCADE,
    changed_by  UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    old_status  VARCHAR(20),
    new_status  VARCHAR(20),
    comment     TEXT,
    version     INT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_iv_reviews_updated_at
    BEFORE UPDATE ON iv_reviews
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ────────────────────────────────────────────────────────────
-- MODULE 9: EXTERNAL VERIFICATION
-- ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS ev_verifiers (
    id              SERIAL PRIMARY KEY,
    user_id         UUID UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
    full_name       VARCHAR(200) NOT NULL,
    email           VARCHAR(100),
    organization    VARCHAR(200),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ev_assignments (
    id              SERIAL PRIMARY KEY,
    verifier_id     INT  NOT NULL REFERENCES ev_verifiers(id)  ON DELETE CASCADE,
    department_id   INT  NOT NULL REFERENCES departments(id)   ON DELETE CASCADE,
    unit_id         INT  REFERENCES units(id)                  ON DELETE SET NULL,
    year            INT  NOT NULL DEFAULT EXTRACT(YEAR FROM NOW())::INT,
    term            INT  NOT NULL DEFAULT 1,
    visit_date      DATE,
    status          VARCHAR(20) NOT NULL DEFAULT 'scheduled'
                    CHECK (status IN ('scheduled','in_progress','completed','cancelled')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ev_reports (
    id                  SERIAL PRIMARY KEY,
    assignment_id       INT  NOT NULL REFERENCES ev_assignments(id) ON DELETE CASCADE,
    -- Moderation findings
    compliance_score    INT  CHECK (compliance_score BETWEEN 0 AND 100),
    overall_verdict     VARCHAR(20) NOT NULL DEFAULT 'pending'
                        CHECK (overall_verdict IN ('pending','satisfactory','unsatisfactory','conditional')),
    findings            TEXT,
    recommendations     TEXT,
    -- Digital signature
    verifier_signature  TEXT,
    signed_at           TIMESTAMPTZ,
    -- Approval
    approved_by         UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    approved_at         TIMESTAMPTZ,
    -- Audit
    version             INT NOT NULL DEFAULT 1,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ev_report_history (
    id          BIGSERIAL PRIMARY KEY,
    report_id   INT NOT NULL REFERENCES ev_reports(id) ON DELETE CASCADE,
    changed_by  UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    action      VARCHAR(50),
    detail      JSONB,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_ev_reports_updated_at
    BEFORE UPDATE ON ev_reports
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ────────────────────────────────────────────────────────────
-- MODULE 10: DUAL TRAINING MANAGEMENT
-- ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS employers (
    id              SERIAL PRIMARY KEY,
    company_name    VARCHAR(200) NOT NULL,
    contact_person  VARCHAR(200),
    email           VARCHAR(100),
    phone           VARCHAR(30),
    address         TEXT,
    industry_sector VARCHAR(100),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS dual_training_allocations (
    id              SERIAL PRIMARY KEY,
    student_id      INT  NOT NULL REFERENCES students(id)  ON DELETE CASCADE,
    employer_id     INT  NOT NULL REFERENCES employers(id) ON DELETE CASCADE,
    trainer_id      INT  REFERENCES trainers(id)           ON DELETE SET NULL,
    start_date      DATE NOT NULL,
    end_date        DATE NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active','completed','withdrawn','suspended')),
    -- Competency tracking
    competencies    JSONB,   -- array of {name, status, date_achieved}
    -- Practical hours
    required_hours  INT NOT NULL DEFAULT 480,
    logged_hours    INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (student_id, employer_id, start_date)
);

CREATE TABLE IF NOT EXISTS dual_training_attendance (
    id              SERIAL PRIMARY KEY,
    allocation_id   INT  NOT NULL REFERENCES dual_training_allocations(id) ON DELETE CASCADE,
    date            DATE NOT NULL,
    check_in        TIME,
    check_out       TIME,
    hours_logged    NUMERIC(4,2) DEFAULT 0,
    status          VARCHAR(20) NOT NULL DEFAULT 'present'
                    CHECK (status IN ('present','absent','late','excused')),
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS dual_training_feedback (
    id              SERIAL PRIMARY KEY,
    allocation_id   INT  NOT NULL REFERENCES dual_training_allocations(id) ON DELETE CASCADE,
    submitted_by    UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    feedback_type   VARCHAR(20) NOT NULL DEFAULT 'weekly'
                    CHECK (feedback_type IN ('weekly','monthly','final')),
    week_number     INT,
    -- Competency scores (1-5)
    punctuality     INT CHECK (punctuality BETWEEN 1 AND 5),
    technical_skills INT CHECK (technical_skills BETWEEN 1 AND 5),
    discipline      INT CHECK (discipline BETWEEN 1 AND 5),
    communication   INT CHECK (communication BETWEEN 1 AND 5),
    safety_awareness INT CHECK (safety_awareness BETWEEN 1 AND 5),
    teamwork        INT CHECK (teamwork BETWEEN 1 AND 5),
    initiative      INT CHECK (initiative BETWEEN 1 AND 5),
    overall_score   NUMERIC(4,2),
    comments        TEXT,
    employer_signature TEXT,
    signed_at       TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_dual_training_updated_at
    BEFORE UPDATE ON dual_training_allocations
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ────────────────────────────────────────────────────────────
-- MODULE 11: INDUSTRIAL ATTACHMENT & DIGITAL LOGBOOK
-- ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS attachment_placements (
    id              SERIAL PRIMARY KEY,
    student_id      INT  NOT NULL REFERENCES students(id)  ON DELETE CASCADE,
    employer_id     INT  REFERENCES employers(id)          ON DELETE SET NULL,
    trainer_id      INT  REFERENCES trainers(id)           ON DELETE SET NULL,
    supervisor_id   UUID REFERENCES auth.users(id)         ON DELETE SET NULL,
    organization    VARCHAR(200) NOT NULL,
    location        VARCHAR(200),
    start_date      DATE NOT NULL,
    end_date        DATE NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active','completed','withdrawn')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Allowed submission slots: 7am,9am,11am,1pm,3pm,5pm,7pm
CREATE TABLE IF NOT EXISTS logbook_entries (
    id              BIGSERIAL PRIMARY KEY,
    placement_id    INT  NOT NULL REFERENCES attachment_placements(id) ON DELETE CASCADE,
    student_id      INT  NOT NULL REFERENCES students(id)              ON DELETE CASCADE,
    -- Submission slot (server-assigned, backdate-prevented)
    submission_slot VARCHAR(10) NOT NULL,   -- '07:00','09:00','11:00','13:00','15:00','17:00','19:00'
    entry_date      DATE NOT NULL,
    submitted_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Activity details
    activity_title  VARCHAR(200) NOT NULL,
    description     TEXT NOT NULL,
    skills_gained   TEXT,
    tools_materials TEXT,
    challenges      TEXT,
    time_spent      NUMERIC(4,2),           -- hours
    -- Evidence (Supabase Storage paths, comma-separated or JSON array)
    evidence_files  TEXT,
    -- Location
    gps_latitude    NUMERIC(10,7),
    gps_longitude   NUMERIC(10,7),
    location_name   VARCHAR(200),
    -- Approval
    status          VARCHAR(20) NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending','approved','rejected')),
    supervisor_comment TEXT,
    approved_by     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    approved_at     TIMESTAMPTZ,
    -- Prevent backdating: entry_date must be <= submitted_at date
    CONSTRAINT no_backdate CHECK (entry_date <= submitted_at::DATE),
    UNIQUE (placement_id, student_id, entry_date, submission_slot)
);

CREATE TABLE IF NOT EXISTS attachment_supervisors (
    id          SERIAL PRIMARY KEY,
    user_id     UUID UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
    full_name   VARCHAR(200) NOT NULL,
    email       VARCHAR(100),
    employer_id INT REFERENCES employers(id) ON DELETE SET NULL,
    phone       VARCHAR(30),
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS supervisor_evaluations (
    id              SERIAL PRIMARY KEY,
    placement_id    INT  NOT NULL REFERENCES attachment_placements(id) ON DELETE CASCADE,
    supervisor_id   UUID NOT NULL REFERENCES auth.users(id)            ON DELETE CASCADE,
    week_number     INT  NOT NULL,
    -- Scores (1-5)
    punctuality     INT CHECK (punctuality BETWEEN 1 AND 5),
    technical_skills INT CHECK (technical_skills BETWEEN 1 AND 5),
    discipline      INT CHECK (discipline BETWEEN 1 AND 5),
    communication   INT CHECK (communication BETWEEN 1 AND 5),
    safety_awareness INT CHECK (safety_awareness BETWEEN 1 AND 5),
    teamwork        INT CHECK (teamwork BETWEEN 1 AND 5),
    initiative      INT CHECK (initiative BETWEEN 1 AND 5),
    overall_score   NUMERIC(4,2),
    comments        TEXT,
    supervisor_signature TEXT,
    signed_at       TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (placement_id, supervisor_id, week_number)
);

-- ────────────────────────────────────────────────────────────
-- RLS: Enable on all new tables (service client bypasses anyway)
-- ────────────────────────────────────────────────────────────

ALTER TABLE exam_series                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE assessment_centers           ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_bookings                ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_booking_units           ENABLE ROW LEVEL SECURITY;
ALTER TABLE iv_assignments               ENABLE ROW LEVEL SECURITY;
ALTER TABLE iv_reviews                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE iv_review_history            ENABLE ROW LEVEL SECURITY;
ALTER TABLE ev_verifiers                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE ev_assignments               ENABLE ROW LEVEL SECURITY;
ALTER TABLE ev_reports                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE ev_report_history            ENABLE ROW LEVEL SECURITY;
ALTER TABLE employers                    ENABLE ROW LEVEL SECURITY;
ALTER TABLE dual_training_allocations    ENABLE ROW LEVEL SECURITY;
ALTER TABLE dual_training_attendance     ENABLE ROW LEVEL SECURITY;
ALTER TABLE dual_training_feedback       ENABLE ROW LEVEL SECURITY;
ALTER TABLE attachment_placements        ENABLE ROW LEVEL SECURITY;
ALTER TABLE logbook_entries              ENABLE ROW LEVEL SECURITY;
ALTER TABLE attachment_supervisors       ENABLE ROW LEVEL SECURITY;
ALTER TABLE supervisor_evaluations       ENABLE ROW LEVEL SECURITY;

-- Super admin: full access to all new tables
DO $$
DECLARE
    tbl TEXT;
    tbls TEXT[] := ARRAY[
        'exam_series','assessment_centers','exam_bookings','exam_booking_units',
        'iv_assignments','iv_reviews','iv_review_history',
        'ev_verifiers','ev_assignments','ev_reports','ev_report_history',
        'employers','dual_training_allocations','dual_training_attendance','dual_training_feedback',
        'attachment_placements','logbook_entries','attachment_supervisors','supervisor_evaluations'
    ];
BEGIN
    FOREACH tbl IN ARRAY tbls LOOP
        EXECUTE format(
            'CREATE POLICY %I ON %I FOR ALL TO authenticated
             USING (current_user_role() = ''super_admin'' AND current_user_active())
             WITH CHECK (current_user_role() = ''super_admin'' AND current_user_active())',
            'sa_full_' || tbl, tbl
        );
    END LOOP;
END $$;

-- Students: read/write their own exam bookings and logbook entries
CREATE POLICY student_own_bookings ON exam_bookings
    FOR ALL TO authenticated
    USING (student_id IN (SELECT id FROM students WHERE user_id = auth.uid()) AND current_user_active())
    WITH CHECK (student_id IN (SELECT id FROM students WHERE user_id = auth.uid()) AND current_user_active());

CREATE POLICY student_own_logbook ON logbook_entries
    FOR ALL TO authenticated
    USING (student_id IN (SELECT id FROM students WHERE user_id = auth.uid()) AND current_user_active())
    WITH CHECK (student_id IN (SELECT id FROM students WHERE user_id = auth.uid()) AND current_user_active());

-- ────────────────────────────────────────────────────────────
-- INDEXES
-- ────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_exam_bookings_student   ON exam_bookings(student_id);
CREATE INDEX IF NOT EXISTS idx_exam_bookings_series    ON exam_bookings(series_id);
CREATE INDEX IF NOT EXISTS idx_exam_bookings_status    ON exam_bookings(status);
CREATE INDEX IF NOT EXISTS idx_logbook_student         ON logbook_entries(student_id);
CREATE INDEX IF NOT EXISTS idx_logbook_placement       ON logbook_entries(placement_id);
CREATE INDEX IF NOT EXISTS idx_logbook_date            ON logbook_entries(entry_date);
CREATE INDEX IF NOT EXISTS idx_dual_alloc_student      ON dual_training_allocations(student_id);
CREATE INDEX IF NOT EXISTS idx_dual_alloc_employer     ON dual_training_allocations(employer_id);
CREATE INDEX IF NOT EXISTS idx_iv_reviews_assignment   ON iv_reviews(assignment_id);
CREATE INDEX IF NOT EXISTS idx_ev_reports_assignment   ON ev_reports(assignment_id);
CREATE INDEX IF NOT EXISTS idx_attach_placements_student ON attachment_placements(student_id);



-- ============================================================
-- SOURCE: supabase_fix_trigger.sql
-- ============================================================

-- ============================================================
-- FIX: Safe auth trigger + Super Admin setup
-- Run this entire file in Supabase SQL Editor
-- ============================================================

-- ── 1. Replace the trigger with a crash-safe version ─────────

CREATE OR REPLACE FUNCTION handle_new_auth_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_role      TEXT;
    v_full_name TEXT;
BEGIN
    v_role := COALESCE(
        NULLIF(TRIM(NEW.raw_user_meta_data->>'role'), ''),
        'student'
    );

    IF v_role NOT IN ('super_admin','dept_admin','trainer','student') THEN
        v_role := 'student';
    END IF;

    v_full_name := COALESCE(
        NULLIF(TRIM(NEW.raw_user_meta_data->>'full_name'), ''),
        NEW.email
    );

    INSERT INTO public.user_profiles (id, full_name, role, is_active)
    VALUES (NEW.id, v_full_name, v_role, TRUE)
    ON CONFLICT (id) DO NOTHING;

    RETURN NEW;
EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'handle_new_auth_user failed for %: %', NEW.id, SQLERRM;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION handle_new_auth_user();


-- ── 2. Backfill any existing auth users missing a profile ────
--    (Runs safely even if user_profiles is empty)

INSERT INTO public.user_profiles (id, full_name, role, is_active)
SELECT
    u.id,
    COALESCE(NULLIF(TRIM(u.raw_user_meta_data->>'full_name'),''), u.email),
    'student',
    TRUE
FROM auth.users u
WHERE NOT EXISTS (
    SELECT 1 FROM public.user_profiles p WHERE p.id = u.id
);


-- ── 3. Promote a user to super_admin ─────────────────────────
--    Replace the email below with your actual admin email,
--    then uncomment and run.

/*
UPDATE public.user_profiles
SET    role = 'super_admin', is_active = TRUE
WHERE  id = (
    SELECT id FROM auth.users
    WHERE  email = 'your-admin@email.com'
    LIMIT  1
);
*/


-- ── 4. Verify ────────────────────────────────────────────────

SELECT
    u.email,
    p.full_name,
    p.role,
    p.is_active
FROM auth.users u
JOIN public.user_profiles p ON p.id = u.id
ORDER BY p.role, u.email;



-- ============================================================
-- SOURCE: link_super_admin_from_auth1.sql
-- ============================================================

-- ============================================================
-- Link Super Admin after creating them in Supabase Auth
-- ============================================================
-- STEP 1: Supabase Dashboard → Authentication → Users → Add user
--         Email:    superadmin@ttieportfolio.ac.ke  (your choice)
--         Password: your secure password
--         ✓ Auto Confirm User
--
-- STEP 2: Run this SQL (change email/name if needed)

INSERT INTO public.user_profiles (id, full_name, role, is_active)
SELECT
  au.id,
  'Super Administrator',
  'super_admin',
  TRUE
FROM auth.users au
WHERE lower(au.email) = lower('superadmin@ttieportfolio.ac.ke')
ON CONFLICT (id) DO UPDATE SET
  role      = EXCLUDED.role,
  full_name = EXCLUDED.full_name,
  is_active = TRUE;


-- ============================================================
-- SOURCE: supabase_promote_superadmin.sql
-- ============================================================

-- ============================================================
-- Promote your account to super_admin
-- Run in Supabase SQL Editor
-- Replace the email with YOUR actual email address
-- ============================================================

UPDATE public.user_profiles
SET 
    role      = 'super_admin',
    is_active = TRUE
WHERE id = (
    SELECT id 
    FROM auth.users 
    WHERE email = 'YOUR_EMAIL_HERE'   -- ← change this
    LIMIT 1
);

-- Verify it worked:
SELECT 
    u.email,
    p.role,
    p.is_active
FROM auth.users u
JOIN public.user_profiles p ON p.id = u.id
ORDER BY u.created_at DESC;



-- ============================================================
